import path from 'path';
import { createReadStream } from 'fs';
import { readFile, stat } from 'fs/promises';
import { Readable } from 'stream';
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

/**
 * Recordings can be kept on local disk (default — no S3-compatible service
 * required) or uploaded to an S3-compatible bucket (e.g. self-hosted MinIO).
 * Set RECORDING_STORAGE_MODE=s3 to switch once that's set up; local mode
 * just needs a directory with enough space (RECORDING_LOCAL_DIR).
 */
export const RECORDING_STORAGE_MODE: 'local' | 's3' = process.env.RECORDING_STORAGE_MODE === 's3' ? 's3' : 'local';

const RECORDING_LOCAL_DIR = path.resolve(process.env.RECORDING_LOCAL_DIR ?? path.join(process.cwd(), 'recordings'));

/**
 * Resolves a recording key to an absolute path inside RECORDING_LOCAL_DIR,
 * rejecting anything that would escape it (recording keys are generated by
 * this app, not user input, but this is cheap insurance against a bad key
 * ever reaching the filesystem).
 */
export function getRecordingLocalPath(key: string): string {
  const resolved = path.resolve(RECORDING_LOCAL_DIR, key);
  if (resolved !== RECORDING_LOCAL_DIR && !resolved.startsWith(RECORDING_LOCAL_DIR + path.sep)) {
    throw new Error(`Invalid recording key: ${key}`);
  }
  return resolved;
}

// Constructed lazily — the AWS SDK doesn't validate credentials eagerly like
// the OpenAI SDK does, but keeping this consistent with the other lazy
// client getters in this codebase avoids surprises either way.
export function getRecordingS3Client(): S3Client {
  return new S3Client({
    endpoint: process.env.RECORDING_S3_ENDPOINT,
    region: process.env.RECORDING_S3_REGION ?? 'us-east-1',
    forcePathStyle: true,
    credentials: {
      accessKeyId: process.env.RECORDING_S3_ACCESS_KEY_ID ?? '',
      secretAccessKey: process.env.RECORDING_S3_SECRET_ACCESS_KEY ?? ''
    }
  });
}

export const RECORDING_BUCKET = process.env.RECORDING_S3_BUCKET ?? '';

/** A short-lived, credential-free URL the browser can stream/download the recording from directly. S3 mode only. */
export async function getRecordingDownloadUrl(key: string, expiresInSeconds = 3600): Promise<string> {
  const command = new GetObjectCommand({ Bucket: RECORDING_BUCKET, Key: key });
  return getSignedUrl(getRecordingS3Client(), command, { expiresIn: expiresInSeconds });
}

/** Reads a full recording into memory (used for transcription) — local disk or S3, whichever mode is active. */
export async function getRecordingBuffer(key: string): Promise<Buffer> {
  if (RECORDING_STORAGE_MODE === 'local') {
    return readFile(getRecordingLocalPath(key));
  }

  const response = await getRecordingS3Client().send(new GetObjectCommand({ Bucket: RECORDING_BUCKET, Key: key }));
  const chunks: Buffer[] = [];
  for await (const chunk of response.Body as AsyncIterable<Buffer>) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks);
}

/**
 * Streams a locally-stored recording as an HTTP response, honoring Range
 * requests so <audio>/<video> scrubbing works. Used by the
 * .../recording/file routes when RECORDING_STORAGE_MODE is 'local'.
 */
export async function streamLocalRecording(request: Request, key: string, contentType: string): Promise<Response> {
  const filePath = getRecordingLocalPath(key);

  let size: number;
  try {
    size = (await stat(filePath)).size;
  } catch {
    return new Response(JSON.stringify({ error: 'Recording file not found on disk.' }), {
      status: 404,
      headers: { 'Content-Type': 'application/json' }
    });
  }

  const range = request.headers.get('range');
  if (!range) {
    const body = Readable.toWeb(createReadStream(filePath)) as ReadableStream;
    return new Response(body, {
      status: 200,
      headers: { 'Content-Type': contentType, 'Content-Length': String(size), 'Accept-Ranges': 'bytes' }
    });
  }

  const match = /bytes=(\d+)-(\d*)/.exec(range);
  const start = match?.[1] ? Number(match[1]) : 0;
  const end = match?.[2] ? Number(match[2]) : size - 1;

  const body = Readable.toWeb(createReadStream(filePath, { start, end })) as ReadableStream;
  return new Response(body, {
    status: 206,
    headers: {
      'Content-Type': contentType,
      'Content-Length': String(end - start + 1),
      'Content-Range': `bytes ${start}-${end}/${size}`,
      'Accept-Ranges': 'bytes'
    }
  });
}
